spring:
  profiles:
    active: "original"
  banner:
    location: "classpath:logo-app"

  datasource:
    url: jdbc:h2:file:./flashcards_db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

pl:
  edu:
    pja:
      tpo02:
        filename: "src/main/resources/words.csv"